---
- name: "DESK_THUNAR_CONFIGURE - Copy thunar/xfce4 dotfiles"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/dotfiles/{{ item.src }}"
    dest: "{{ item.entity.home }}/{{ item.src }}"
    owner: "{{ item.entity.name }}"
    group: "{{ item.entity.group | default(item.entity.name) }}"
    mode: "0700"
  loop: "{{ thunar_copy_items }}"
  loop_control:
    label: "{{ item.entity.name }}/{{ item.src }}"
  become: true
