---
- name: "DESK_THUNAR_INSTALL - Install thunar core packages"
  ansible.builtin.apt:
    name: "{{ thunar_packages }}"
    state: present
  become: true

- name: "DESK_THUNAR_INSTALL - Install XFCE4 packages"
  ansible.builtin.apt:
    name: "{{ thunar_xfce_packages }}"
    state: present
  become: true
