---
- name: Compute thunar per-user facts
  ansible.builtin.include_tasks: facts.yml
- name: Install thunar and xfce helpers
  ansible.builtin.include_tasks: install.yml

- name: Configure per-user thunar dotfiles
  ansible.builtin.include_tasks: configure.yml
