---
- name: "DESK_THUNAR_MAIN - Resolve users"
  ansible.builtin.include_tasks: resolve.yml

- name: "DESK_THUNAR_MAIN - Install thunar packages"
  ansible.builtin.include_tasks: install.yml

- name: "DESK_THUNAR_MAIN - Configure per-user thunar dotfiles"
  ansible.builtin.include_tasks: configure.yml
