---
- name: Compute qtile per-user facts
  ansible.builtin.include_tasks: facts.yml
- name: Install qtile system and per-user prerequisites
  ansible.builtin.include_tasks: install.yml

- name: Configure per-user qtile dotfiles
  ansible.builtin.include_tasks: configure.yml
