---
- name: Install brave package prereqs
  ansible.builtin.package:
    name: "{{ brave_packages }}"
    state: present
    update_cache: true
  become: true

- name: Download Brave GPG keyring
  ansible.builtin.get_url:
    url: "{{ brave_repo_url }}brave-browser-archive-keyring.gpg"
    dest: "{{ brave_keyring_path }}"
    mode: "0644"
  become: true

- name: Add Brave apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ brave_keyring_path }}] {{ brave_repo_url }} stable main"
    filename: "{{ brave_apt_filename }}"
    state: present
  become: true

- name: Install Brave browser package
  ansible.builtin.package:
    name: brave-browser
    state: present
    update_cache: true
  become: true
