---
- name: Copy per-user wm config files (0600 mode)
  ansible.builtin.copy:
    src: "{{ role_path }}/files/dotfiles/{{ item.src }}"
    dest: "{{ item.entity.home }}/{{ item.src }}"
    owner: "{{ item.entity.name }}"
    group: "{{ item.entity.group | default(item.entity.name) }}"
    mode: "0600"
  loop: "{{ wm_copy_items }}"
  when: item.src == '.config/picom.conf'
  loop_control:
    label: "{{ item.entity.name }}/{{ item.src }}"
  become: true

- name: Copy per-user wm scripts (0700 mode)
  ansible.builtin.copy:
    src: "{{ role_path }}/files/dotfiles/{{ item.src }}"
    dest: "{{ item.entity.home }}/{{ item.src }}"
    owner: "{{ item.entity.name }}"
    group: "{{ item.entity.group | default(item.entity.name) }}"
    mode: "0700"
  loop: "{{ wm_copy_items }}"
  when: item.src != '.config/picom.conf'
  loop_control:
    label: "{{ item.entity.name }}/{{ item.src }}"
  become: true
