---
- name: WM - Compute per-user data
  ansible.builtin.include_tasks: compute.yml
- name: "DESK_WM_MAIN - Install window manager packages"
  ansible.builtin.include_tasks: install.yml

- name: "DESK_WM_MAIN - Configure per-user wm dotfiles"
  ansible.builtin.include_tasks: configure.yml
