---
- name: WM - Compute per-user facts
  ansible.builtin.include_tasks: facts.yml
- name: "DESK_WM_MAIN - Install window manager packages"
  ansible.builtin.include_tasks: install.yml

- name: "DESK_WM_MAIN - Configure per-user wm dotfiles"
  ansible.builtin.include_tasks: configure.yml
