---
- name: Compute rofi per-user facts
  ansible.builtin.include_tasks: facts.yml
- name: Install rofi and themes
  ansible.builtin.include_tasks: install.yml

- name: Configure per-user rofi dotfiles
  ansible.builtin.include_tasks: configure.yml
