---
- name: ROFI - Compute per-user facts
  ansible.builtin.include_tasks: facts.yml
- name: "DESK_ROFI_MAIN - Install rofi packages"
  ansible.builtin.include_tasks: install.yml

- name: "DESK_ROFI_MAIN - Configure per-user rofi dotfiles and scripts"
  ansible.builtin.include_tasks: configure.yml
