---

x11_packages:
  - xorg
  - xserver-xorg-video-nouveau
  - xserver-xorg-video-vesa
  - xterm
  - mesa-utils
  - freeglut3-dev
  - libglm-dev
  - libao-dev
  - libxinerama-dev
  - libxft-dev
  - libglu1-mesa-dev
