---
- name: Install plymouth packages
  ansible.builtin.package:
    name: "{{ plymouth_packages }}"
    state: present
  become: true

- name: Copy plymouth theme files
  ansible.builtin.copy:
    src: "{{ plymouth_themes_dir }}/text/"
    dest: "{{ plymouth_themes_dir }}/{{ plymouth_default_theme }}/"
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Copy plymouth .plymouth file
  ansible.builtin.copy:
    src: "{{ plymouth_themes_dir }}/text/text.plymouth"
    dest: "{{ plymouth_themes_dir }}/{{ plymouth_default_theme }}/{{ plymouth_default_theme }}.plymouth"
    owner: root
    group: root
    mode: "0644"
  become: true

# - name: "DESK_PLYMOUTH_INSTALL - Copy renamed .script"
#   ansible.builtin.copy:
#     src: "{{ plymouth_themes_dir }}/text/text.script"
#     dest: "{{ plymouth_themes_dir }}/{{ plymouth_default_theme }}/{{ plymouth_default_theme }}.script"
#     owner: root
#     group: root
#     mode: "0644"
#   become: true

# - name: "DESK_PLYMOUTH_INSTALL - Replace 'text' in .script"
#   ansible.builtin.replace:
#     path: "{{ plymouth_themes_dir }}/{{ plymouth_default_theme }}/{{ plymouth_default_theme }}.script"
#     regexp: "text"
#     replace: "{{ plymouth_default_theme }}"
#   become: true

- name: Replace 'text' in .plymouth with default theme name
  ansible.builtin.replace:
    path: "{{ plymouth_themes_dir }}/{{ plymouth_default_theme }}/{{ plymouth_default_theme }}.plymouth"
    regexp: "text"
    replace: "{{ plymouth_default_theme }}"
  become: true

- name: Copy bootsplash background image
  ansible.builtin.copy:
    src: "/boot/grub/themes/{{ plymouth_default_theme }}/background.png"
    dest: "{{ plymouth_themes_dir }}/{{ plymouth_default_theme }}/"
    owner: root
    group: root
    mode: "0644"
  become: true

# - name: "DESK_PLYMOUTH_INSTALL - plymouth-set-default-theme"
#   ansible.builtin.command: "plymouth-set-default-theme {{ plymouth_default_theme }}"
#   changed_when: true
#   become: true
#
# - name: "DESK_PLYMOUTH_INSTALL - plymouth-set-default-theme -R (rebuild initrd)"
#   ansible.builtin.command: plymouth-set-default-theme -R
#   changed_when: true
#   become: true
