---
- name: Desktop base install
  hosts: all
  become: true
  roles:
    - role: mps.desktop.x11
    - role: mps.desktop.gnometools
    - role: mps.desktop.grubmenu
    # - role: mps.desktop.plymouth
    - role: mps.desktop.lightdm
