---
- name: Copy GTK config files (0600 mode)
  ansible.builtin.copy:
    src: "{{ role_path }}/files/dotfiles/{{ item.src }}"
    dest: "{{ item.entity.home }}/{{ item.src }}"
    owner: "{{ item.entity.name }}"
    group: "{{ item.entity.group | default(item.entity.name) }}"
    mode: "0600"
  loop: "{{ essentials_gtk_copy_items }}"
  when: item.src == '.gtkrc-2.0'
  loop_control:
    label: "{{ item.entity.name }}/{{ item.src }}"

- name: Copy GTK config directories (0700 mode)
  ansible.builtin.copy:
    src: "{{ role_path }}/files/dotfiles/{{ item.src }}"
    dest: "{{ item.entity.home }}/{{ item.src }}"
    owner: "{{ item.entity.name }}"
    group: "{{ item.entity.group | default(item.entity.name) }}"
    mode: "0700"
  loop: "{{ essentials_gtk_copy_items }}"
  when: item.src != '.gtkrc-2.0'
  loop_control:
    label: "{{ item.entity.name }}/{{ item.src }}"

- name: Copy gedit config per user
  ansible.builtin.copy:
    src: "{{ role_path }}/files/dotfiles/{{ item.src }}"
    dest: "{{ item.entity.home }}/{{ item.src | dirname }}/"
    owner: "{{ item.entity.name }}"
    group: "{{ item.entity.group | default(item.entity.name) }}"
    mode: "0600"
  loop: "{{ essentials_gedit_copy_items }}"
  loop_control:
    label: "{{ item.entity.name }}/{{ item.src }}"

- name: Copy dconf config per user
  ansible.builtin.copy:
    src: "{{ role_path }}/files/dotfiles/{{ item.src }}"
    dest: "{{ item.entity.home }}/{{ item.src | dirname }}/"
    owner: "{{ item.entity.name }}"
    group: "{{ item.entity.group | default(item.entity.name) }}"
    mode: "0600"
  loop: "{{ essentials_dconf_copy_items }}"
  loop_control:
    label: "{{ item.entity.name }}/{{ item.src }}"
