---
- name: "DESK_ESSENTIALS_INSTALL - Install base desktop packages"
  ansible.builtin.apt:
    name: "{{ essentials_packages_base }}"
    state: present
  become: true

- name: "DESK_ESSENTIALS_INSTALL - Install sound stack packages"
  ansible.builtin.apt:
    name: "{{ essentials_packages_sound }}"
    state: present
  become: true

- name: "DESK_ESSENTIALS_INSTALL - Install XDG utility packages"
  ansible.builtin.apt:
    name: "{{ essentials_packages_xdg }}"
    state: present
  become: true

- name: "DESK_ESSENTIALS_INSTALL - Ensure images target dir exists"
  ansible.builtin.file:
    path: "{{ essentials_bootsplash_dst | dirname }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: "DESK_ESSENTIALS_INSTALL - Ensure wallpapers target dir exists"
  ansible.builtin.file:
    path: "{{ essentials_wallpapers_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: "DESK_ESSENTIALS_INSTALL - Copy bootsplash image"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/dotfiles/images/{{ essentials_bootsplash_src }}"
    dest: "{{ essentials_bootsplash_dst }}"
    owner: root
    group: root
    mode: "0644"
  become: true

- name: "DESK_ESSENTIALS_INSTALL - Copy wallpapers"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/dotfiles/wallpaper/{{ item }}"
    dest: "{{ essentials_wallpapers_dir }}/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ essentials_wallpapers_list }}"
  become: true
