---
- name: Compute essentials per-user facts
  ansible.builtin.include_tasks: facts.yml
- name: Install system packages and images
  ansible.builtin.include_tasks: install.yml

- name: Configure per-user dotfiles and system images
  ansible.builtin.include_tasks: configure.yml
