---
- name: "DESK_ESSENTIALS_MAIN - Install system packages"
  ansible.builtin.include_tasks: install.yml

- name: "DESK_ESSENTIALS_MAIN - Configure per-user dotfiles and system images"
  ansible.builtin.include_tasks: configure.yml
